### ISSUE TITLE
Add links to Get involved form

### ISSUE THREAD

**Issue by ioana-chiorean** [emmairwin/community_curriculum#17]
Go here: http://education.mozilla-community.org/modules/about_contribute/about-this-course/
Look at the 
Get Involved!part 

Also there should be for the footer text too ( Reported firstly here: https://github.com/emmairwin/mozilla-community-edu/issues/17) 

---

Suggestions:
- Writing content - maybe MDN? https://developer.mozilla.org/en-US/docs/Project:MDN/Contributing 
- Researching - Mozilla Science? 
- QA/Proofreading - QMO? https://quality.mozilla.org/
- Facilitating/Delivering online material - MDN?
- Coding(CSS/SASS/HTML/JavaScript/Ruby/Liquid) - MDN, http://whatcanidoformozilla.org, http://www.joshmatthews.net/bugsahoy ?

**Comment by SOFTowaha** [comment]
[This](http://education.mozilla-community.org/modules/about_contribute/about-this-course/) link shows a 404 error; 
Please fix it;

**Comment by emmairwin** [comment]
@SOFTowaha some links have changed in recent months, if you didn't come by that link through the actual site, then I would just ignore it.    T hanks

**Comment by ioana-chiorean** [comment]
This is not under development anymore. 😢 
Will reopen if this will restart! 🍀 ✌🏽
