### ISSUE TITLE
Supercharge your Community  - Curriculum QA

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/community_curriculum#23]
Please leave comments here for any issues you find or improvements you suggest.
Thanks in advance!
#### Files to Review
- [Intro](https://github.com/emmairwin/community_curriculum/blob/master/leadership/building_for_action_impact/super_charge_your_community/introduction.md)
- [Personas](https://github.com/emmairwin/community_curriculum/blob/master/leadership/building_for_action_impact/super_charge_your_community/persona_activity.md)
- [Pathway](https://github.com/emmairwin/community_curriculum/blob/master/leadership/building_for_action_impact/super_charge_your_community/pathway_step_activity.md)
- [Wrap Up](https://github.com/emmairwin/community_curriculum/blob/master/leadership/building_for_action_impact/super_charge_your_community/wrap_up.md)

**Comment by iamVP7** [comment]
@emmairwin  i tried to click on links, getting 404. Can you update the links.

**Comment by emmairwin** [comment]
@iamVP7 sorry about that, I did do some reorging - updated!

**Comment by asdofindia** [comment]
In, https://github.com/emmairwin/community_curriculum/blob/master/leadership/building_for_action_impact/super_charge_your_community/introduction.md#audience 
is it Mozilla Indonesia **FSA** lead?

In, https://github.com/emmairwin/community_curriculum/blob/master/leadership/building_for_action_impact/super_charge_your_community/pathway_step_activity.md#visualizing-participation-steps---10-minutes 

> Q1 Tell the story of how one of your personas came or might come your project?

^ isn't clear for me

Also, in, https://github.com/emmairwin/community_curriculum/blob/master/leadership/building_for_action_impact/super_charge_your_community/pathway_step_activity.md#path-mapping---10-minutes-

> How might we bring our persona, as they arrive in our community closer to the potenial of their participation which is _______ ?

^ It isn't clear what is to be filled in the _____
