### ISSUE TITLE
Six Degrees of Mozilla

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/community_curriculum#24]
This curriculum explores networked action for community questions, issues, complaints and concerns through the people we are connected to.

Looking for QA on
- [Introduction](https://github.com/emmairwin/community_curriculum/blob/master/leadership/essential_mozilla/six_degrees_of_mitchell_baker/introduction.md)
- [Visualizing Networks](https://github.com/emmairwin/community_curriculum/blob/master/leadership/essential_mozilla/six_degrees_of_mitchell_baker/networking_solutions.md)

**Comment by Amena-Islam** [comment]
@emmairwin those links showing 404, will you please have a look.

**Comment by asdofindia** [comment]
In, https://github.com/emmairwin/community_curriculum/blob/master/leadership/essential_mozilla/six_degrees_of_mozilla/introduction.md#format 
s/challanges/challenges/g

https://github.com/emmairwin/community_curriculum/blob/master/leadership/essential_mozilla/six_degrees_of_mozilla/networking_solutions.md#ice-breaker
`why` has become `hwy`

https://github.com/emmairwin/community_curriculum/blob/master/leadership/essential_mozilla/six_degrees_of_mozilla/networking_solutions.md#wrap-up
Grammar in `We are also be the creators of new networks as leaders.`

https://github.com/emmairwin/community_curriculum/blob/master/leadership/essential_mozilla/six_degrees_of_mozilla/networking_solutions.md#introduction---degree and https://github.com/emmairwin/community_curriculum/blob/master/leadership/essential_mozilla/six_degrees_of_mozilla/introduction.md#degree are redundant

https://github.com/emmairwin/community_curriculum/blob/master/leadership/essential_mozilla/six_degrees_of_mozilla/networking_solutions.md#visualizing-networks 
`through of of the`

Also, while imagining myself doing "Visualizing Networks", should all connections be made to Mitchell as an end point or is it okay to end at any decision maker? And, is it okay to use the mozilla wiki or IRC to complete this activity (should participants have/know connections beforehand, or can/will this activity be used as a starting point for them to build connections?)

**Comment by emmairwin** [comment]
Thanks @asdofindia
