### ISSUE TITLE
Building your Community Credentials

### ISSUE THREAD

**Issue by emmairwin** [emmairwin/community_curriculum#25]
- [Introduction](https://github.com/emmairwin/community_curriculum/blob/master/leadership/empowering_teams_people/building_your_community_credentials/introduction.md)
- [Strengths & Credentials](https://github.com/emmairwin/community_curriculum/blob/master/leadership/empowering_teams_people/building_your_community_credentials/mozilla_identity.md)

Looking for QA , but also the credentials themselves need fleshed out a bit more, what should tech cred look like? What should they tell about someone, what should they embody?

**Comment by ioana-chiorean** [comment]
@emmairwin is this still needed?
